### ISSUE TITLE
Cannot be launched

### ISSUE THREAD

**Issue by probonopd** [bukinoshita/taskr#32]
On Xubuntu 16.04:

```
me@host:~$ Downloads/whatsapp-desktop-0.4.2-x86_64\(1\).AppImage 
installed: X-AppImage-BuildId=40c80560-f2f1-11a7-0562-5b6d62f9291c image: X-AppImage-BuildId=40c80560-f2f1-11a7-0562-5b6d62f9291c
[18:08:46.230] [info] Log init, file /home/me/.config/whatsapp-desktop/log.log
[18:08:46.235] [info] Loading locale en_US
module.js:472
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/tmp/.mount_whatsa5dFvdf/app/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/tmp/.mount_whatsa5dFvdf/app/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/tmp/.mount_whatsa5dFvdf/app/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)
```

**Comment by bukinoshita** [comment]
Hey, sorry for that. Linux and Windows are totally untested beta. I tried to compile with `electron-packager` but it seems Windows/Linux versions are broken.

That being said I want to follow this issue [here](https://github.com/bukinoshita/taskr/issues/5). As soon as I figure it out how to compile without any errors I'll release a new version.

I'll also remove linux/windows version from the release for now.
