### ISSUE TITLE
Please provide an AppImage on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [bukinoshita/taskr#5]
Looks like this project is already configured to build an AppImage, but the AppImage is not available for download on GitHub Releases.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by probonopd** [comment]
In fact, the AppImage generation is already configured here:

https://github.com/bukinoshita/taskr/blob/72c4e785d9191ff0528811617c20d140fe100a58/package.json#L36

So it should now be a matter of building it and uploading it to GitHub Releases.
Thanks!

**Comment by bukinoshita** [comment]
hi @probonopd.

When I run:
```bash
$ electron-builder --linux
```
I get this weird bug that I'm not sure what's happening, that's why I didn't release an AppImage yet

```
Error: Exit code: 4. Command failed: sips --resampleHeightWidth 24 24 /private/var/folders/zv/8qvntrsn12zds10_ktqsv75c0000gp/T/temp-dir-BrdoGQ/2.iconset/icon_256x256.png --out /private/var/folders/zv/8qvntrsn12zds10_ktqsv75c0000gp/T/temp-dir-BrdoGQ/2.iconset/icon_24x24.png
Warning: /private/var/folders/zv/8qvntrsn12zds10_ktqsv75c0000gp/T/temp-dir-BrdoGQ/2.iconset/icon_256x256.png not a valid file - skipping
Error 4: no file was specified
Try 'sips --help' for help using this tool

Warning: /private/var/folders/zv/8qvntrsn12zds10_ktqsv75c0000gp/T/temp-dir-BrdoGQ/2.iconset/icon_256x256.png not a valid file - skipping
Error 4: no file was specified
Try 'sips --help' for help using this tool

    at /Users/bukinoshita/github/taskr/node_modules/builder-util/src/util.ts:109:16
    at ChildProcess.exithandler (child_process.js:279:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at exec (/Users/bukinoshita/github/taskr/node_modules/builder-util/src/util.ts:77:3)
    at resizeImage (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:264:12)
    at resize (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:184:75)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:187:46
    at Generator.next (<anonymous>)
    at go$readdir$cb (/Users/bukinoshita/github/taskr/node_modules/graceful-fs/graceful-fs.js:149:14)
From previous event:
    at LinuxTargetHelper.createFromIcns (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/targets/LinuxTargetHelper.js:245:11)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:62:25
From previous event:
    at LinuxTargetHelper.computeDesktopIcons (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/targets/LinuxTargetHelper.js:97:11)
    at Lazy.LinuxTargetHelper.iconPromise.Lazy (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:19:54)
    at Lazy.get value [as value] (/Users/bukinoshita/github/taskr/node_modules/lazy-val/src/main.ts:18:23)
    at LinuxTargetHelper.get icons [as icons] (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:27:29)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/targets/AppImageTarget.ts:145:61
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (/Users/bukinoshita/github/taskr/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:137:15)
From previous event:
    at AppImageTarget.copyIcons (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/targets/AppImageTarget.js:225:11)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/targets/AppImageTarget.ts:55:37
    at Generator.next (<anonymous>)
From previous event:
    at AppImageTarget.build (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/targets/AppImageTarget.js:191:11)
    at taskManager.addTask.default.map.it (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/platformPackager.ts:120:85)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/platformPackager.ts:120:41)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/platformPackager.ts:116:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at LinuxPackager.pack (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/platformPackager.js:195:11)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/packager.ts:345:24
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (/Users/bukinoshita/github/taskr/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:137:15)
From previous event:
    at Packager.doBuild (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/packager.js:407:11)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/packager.ts:289:52
From previous event:
    at Packager._build (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/packager.js:351:11)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/packager.ts:259:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at Packager.build (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/packager.js:311:11)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder/src/builder.ts:287:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (/Users/bukinoshita/github/taskr/node_modules/electron-builder/out/builder.js:61:21)
    at build (/Users/bukinoshita/github/taskr/node_modules/electron-builder/src/builder.ts:257:10)
    at then (/Users/bukinoshita/github/taskr/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at Object.args [as handler] (/Users/bukinoshita/github/taskr/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at Object.runCommand (/Users/bukinoshita/github/taskr/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/Users/bukinoshita/github/taskr/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/Users/bukinoshita/github/taskr/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/bukinoshita/github/taskr/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by probonopd** [comment]
Looks like on macOS the icon conversion is not working properly. Ping @develar

**Comment by develar** [comment]
@bukinoshita Please try pre-release version 19.53.0

**Comment by develar** [comment]
And ensure that your icns file contains at least 256x256 icon (better 512).

**Comment by bukinoshita** [comment]
Updated to `19.53.0` and icns file 256x256

returning me an error:

```
$ electron-builder --linux
  • electron-builder version=19.53.0
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/electron-builder.yaml
  • no native production dependencies
  • packaging       platform=linux arch=x64 electron=1.7.10 appOutDir=dist/linux-unpacked
  • building        target=AppImage arch=x64 file=dist/taskr-0.2.2-x86_64.AppImage
TypeError: A value undefined was yielded that could not be treated as a promise

    See http://goo.gl/MqrFmX

From coroutine:
    at Promise.coroutine (/Users/bukinoshita/github/taskr/node_modules/bluebird/js/release/generators.js:194:17)
    at LinuxTargetHelper.createFromIcns (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/targets/LinuxTargetHelper.js:198:68)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:62:25
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/Users/bukinoshita/github/taskr/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/Users/bukinoshita/github/taskr/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/Users/bukinoshita/github/taskr/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/bukinoshita/github/taskr/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/bukinoshita/github/taskr/node_modules/bluebird/js/release/promise.js:693:18)
    at LinuxTargetHelper.createFromIcns (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/targets/LinuxTargetHelper.js:198:68)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:62:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at LinuxTargetHelper.createFromIcns (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/targets/LinuxTargetHelper.js:214:11)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:62:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
From previous event:
    at LinuxTargetHelper.computeDesktopIcons (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/targets/LinuxTargetHelper.js:95:11)
    at Lazy.LinuxTargetHelper.iconPromise.Lazy (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:19:54)
    at Lazy.get value [as value] (/Users/bukinoshita/github/taskr/node_modules/lazy-val/src/main.ts:18:23)
    at LinuxTargetHelper.get icons [as icons] (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:27:29)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/targets/AppImageTarget.ts:137:61
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (/Users/bukinoshita/github/taskr/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:137:15)
From previous event:
    at AppImageTarget.copyIcons (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/targets/AppImageTarget.js:220:11)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/targets/AppImageTarget.ts:53:37
    at Generator.next (<anonymous>)
From previous event:
    at AppImageTarget.build (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/targets/AppImageTarget.js:186:11)
    at taskManager.addTask.default.map.it (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/platformPackager.ts:121:67)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/platformPackager.ts:121:23)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/platformPackager.ts:116:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at LinuxPackager.pack (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/platformPackager.js:195:11)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/packager.ts:355:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/bukinoshita/github/taskr/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/bukinoshita/github/taskr/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at Packager.doBuild (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/packager.js:419:11)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/packager.ts:299:52
    at Generator.next (<anonymous>)
    at /Users/bukinoshita/github/taskr/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/bukinoshita/github/taskr/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:137:15)
From previous event:
    at Packager._build (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/packager.js:363:11)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/packager.ts:261:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at Packager.build (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/packager.js:319:11)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder/src/builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (/Users/bukinoshita/github/taskr/node_modules/electron-builder/out/builder.js:61:21)
    at build (/Users/bukinoshita/github/taskr/node_modules/electron-builder/src/builder.ts:280:10)
    at then (/Users/bukinoshita/github/taskr/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at Object.args [as handler] (/Users/bukinoshita/github/taskr/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at Object.runCommand (/Users/bukinoshita/github/taskr/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/Users/bukinoshita/github/taskr/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/Users/bukinoshita/github/taskr/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/bukinoshita/github/taskr/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by probonopd** [comment]
@develar do you know what might be causing this? Thanks.

**Comment by bukinoshita** [comment]
updated to `electron-builder@19.55.1` and getting this now

```bash
$ electron-builder --linux
  • electron-builder version=19.55.1
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/electron-builder.yaml
  • no native production dependencies
  • packaging       platform=linux arch=x64 electron=1.7.10 appOutDir=dist/linux-unpacked
  • building        target=AppImage arch=x64 file=dist/Taskr-0.4.0-x86_64.AppImage
Error: Exit code: 1. Command failed: /Users/bukinoshita/Library/Caches/electron-builder/app-builder/app-builder-v0.6.0-x64/app-builder icon --format set --root /Users/bukinoshita/github/taskr/build --root /Users/bukinoshita/github/taskr --input icons --input /Users/bukinoshita/github/taskr/main/static/icon.icns --input /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/templates/linux/electron-icons
   ⨯ open : no such file or directory
github.com/develar/app-builder/icons.LoadImage
        /Users/develar/go/src/github.com/develar/app-builder/icons/icons-api.go:38
github.com/develar/app-builder/icons.multiResizeImage
        /Users/develar/go/src/github.com/develar/app-builder/icons/icns-to-png.go:110
github.com/develar/app-builder/icons.ConvertIcnsToPng
        /Users/develar/go/src/github.com/develar/app-builder/icons/icns-to-png.go:91
github.com/develar/app-builder/icons.ConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/icons/icon-converter.go:177
main.doConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/main.go:61
main.main
        /Users/develar/go/src/github.com/develar/app-builder/main.go:44
runtime.main
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/proc.go:195
runtime.goexit
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/asm_amd64.s:2337
github.com/develar/app-builder/icons.multiResizeImage
        /Users/develar/go/src/github.com/develar/app-builder/icons/icns-to-png.go:112
github.com/develar/app-builder/icons.ConvertIcnsToPng
        /Users/develar/go/src/github.com/develar/app-builder/icons/icns-to-png.go:91
github.com/develar/app-builder/icons.ConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/icons/icon-converter.go:177
main.doConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/main.go:61
main.main
        /Users/develar/go/src/github.com/develar/app-builder/main.go:44
runtime.main
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/proc.go:195
runtime.goexit
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/asm_amd64.s:2337
github.com/develar/app-builder/icons.ConvertIcnsToPng
        /Users/develar/go/src/github.com/develar/app-builder/icons/icns-to-png.go:93
github.com/develar/app-builder/icons.ConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/icons/icon-converter.go:177
main.doConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/main.go:61
main.main
        /Users/develar/go/src/github.com/develar/app-builder/main.go:44
runtime.main
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/proc.go:195
runtime.goexit
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/asm_amd64.s:2337
github.com/develar/app-builder/icons.ConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/icons/icon-converter.go:179
main.doConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/main.go:61
main.main
        /Users/develar/go/src/github.com/develar/app-builder/main.go:44
runtime.main
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/proc.go:195
runtime.goexit
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/asm_amd64.s:2337


   ⨯ open : no such file or directory
github.com/develar/app-builder/icons.LoadImage
        /Users/develar/go/src/github.com/develar/app-builder/icons/icons-api.go:38
github.com/develar/app-builder/icons.multiResizeImage
        /Users/develar/go/src/github.com/develar/app-builder/icons/icns-to-png.go:110
github.com/develar/app-builder/icons.ConvertIcnsToPng
        /Users/develar/go/src/github.com/develar/app-builder/icons/icns-to-png.go:91
github.com/develar/app-builder/icons.ConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/icons/icon-converter.go:177
main.doConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/main.go:61
main.main
        /Users/develar/go/src/github.com/develar/app-builder/main.go:44
runtime.main
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/proc.go:195
runtime.goexit
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/asm_amd64.s:2337
github.com/develar/app-builder/icons.multiResizeImage
        /Users/develar/go/src/github.com/develar/app-builder/icons/icns-to-png.go:112
github.com/develar/app-builder/icons.ConvertIcnsToPng
        /Users/develar/go/src/github.com/develar/app-builder/icons/icns-to-png.go:91
github.com/develar/app-builder/icons.ConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/icons/icon-converter.go:177
main.doConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/main.go:61
main.main
        /Users/develar/go/src/github.com/develar/app-builder/main.go:44
runtime.main
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/proc.go:195
runtime.goexit
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/asm_amd64.s:2337
github.com/develar/app-builder/icons.ConvertIcnsToPng
        /Users/develar/go/src/github.com/develar/app-builder/icons/icns-to-png.go:93
github.com/develar/app-builder/icons.ConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/icons/icon-converter.go:177
main.doConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/main.go:61
main.main
        /Users/develar/go/src/github.com/develar/app-builder/main.go:44
runtime.main
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/proc.go:195
runtime.goexit
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/asm_amd64.s:2337
github.com/develar/app-builder/icons.ConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/icons/icon-converter.go:179
main.doConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/main.go:61
main.main
        /Users/develar/go/src/github.com/develar/app-builder/main.go:44
runtime.main
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/proc.go:195
runtime.goexit
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/asm_amd64.s:2337


    at /Users/bukinoshita/github/taskr/node_modules/builder-util/src/util.ts:122:16
    at ChildProcess.exithandler (child_process.js:279:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at exec (/Users/bukinoshita/github/taskr/node_modules/builder-util/src/util.ts:85:3)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/platformPackager.ts:587:23
    at Generator.next (<anonymous>)
    at LOOP (fs.js:1747:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at LinuxPackager.resolveIcon (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/platformPackager.js:626:11)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:35:35
    at Generator.next (<anonymous>)
From previous event:
    at LinuxTargetHelper.computeDesktopIcons (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/targets/LinuxTargetHelper.js:68:11)
    at Lazy.LinuxTargetHelper.iconPromise.Lazy (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:13:54)
    at Lazy.get value [as value] (/Users/bukinoshita/github/taskr/node_modules/lazy-val/src/main.ts:18:23)
    at LinuxTargetHelper.get icons [as icons] (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/targets/LinuxTargetHelper.ts:21:29)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/targets/AppImageTarget.ts:137:61
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (/Users/bukinoshita/github/taskr/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:137:15)
From previous event:
    at AppImageTarget.copyIcons (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/targets/AppImageTarget.js:220:11)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/targets/AppImageTarget.ts:53:37
    at Generator.next (<anonymous>)
From previous event:
    at AppImageTarget.build (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/targets/AppImageTarget.js:186:11)
    at taskManager.addTask.default.map.it (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/platformPackager.ts:120:67)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/platformPackager.ts:120:23)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/platformPackager.ts:115:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at LinuxPackager.pack (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/platformPackager.js:202:11)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/packager.ts:364:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/bukinoshita/github/taskr/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/bukinoshita/github/taskr/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at Packager.doBuild (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/packager.js:432:11)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/packager.ts:308:52
    at Generator.next (<anonymous>)
    at /Users/bukinoshita/github/taskr/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/bukinoshita/github/taskr/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:137:15)
From previous event:
    at Packager._build (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/packager.js:376:11)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/src/packager.ts:270:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at Packager.build (/Users/bukinoshita/github/taskr/node_modules/electron-builder-lib/out/packager.js:332:11)
    at /Users/bukinoshita/github/taskr/node_modules/electron-builder/src/builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (/Users/bukinoshita/github/taskr/node_modules/electron-builder/out/builder.js:61:21)
    at build (/Users/bukinoshita/github/taskr/node_modules/electron-builder/src/builder.ts:280:10)
    at then (/Users/bukinoshita/github/taskr/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at Object.args [as handler] (/Users/bukinoshita/github/taskr/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at Object.runCommand (/Users/bukinoshita/github/taskr/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/bukinoshita/github/taskr/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/Users/bukinoshita/github/taskr/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/bukinoshita/github/taskr/node_modules/electron-builder/src/cli/cli.ts:42:15)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by bukinoshita** [comment]
hey @probonopd, are you using Linux?

Can you try running `electron-builder --linux` on https://github.com/bukinoshita/taskr/tree/v1.0.0 and see if builds an App Image?

**Comment by probonopd** [comment]
So you are running macOS, right?

**Comment by bukinoshita** [comment]
Yes, I'm. That's why I think it's not working.

> Don't expect that you can build app for all platforms on one platform.

https://www.electron.build/multi-platform-build

**Comment by probonopd** [comment]
Does your app have native dependencies? You might want to use a free service like Travis CI.

**Comment by bukinoshita** [comment]
It seems it built for Linux on Travis [here](https://travis-ci.org/bukinoshita/taskr/jobs/331012817). Getting an error on Windows and macOS is not even running(?). Do you know how do I get the dist folder (binaries) from there?

Working on [travis-os](https://github.com/bukinoshita/taskr/tree/travis-os) branch.

**Comment by probonopd** [comment]
Sorry, I don't have much of a clue about how to use electron-builder besides at looking at its documentation, best ask in that project. Thanks.
